service: davidneo

frameworkVersion: "2"

package:
  individually: true

custom:
  esbuild:
    bundle: true
  stage: ${opt:stage}

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  region: ap-southeast-2
  profile: davidneo

functions:
  hello:
    handler: handler.hello
  subscribe:
    handler: src/subscribe.handler
